This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./hni_diss_main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file hni_diss_main.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file hni_diss_main.acr....done (7 lines written, 0 warnings).
Output written in hni_diss_main.acr.
Transcript written in hni_diss_main.alg.
